### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by AdamJCavanaugh** [axpokl/MineSweeperTetris#1]
- The current formatting does not display correctly on GitHub
- I think there should be a link to the game on Steam
- You were reviewed by [RPS](https://www.rockpapershotgun.com/minesweeper-and-tetris-combine-in-minesweeper-tetris-free-on-steam), so may want to link there as well?
- Contribution/compile/build guidelines/etc?

**Comment by axpokl** [comment]
updated
